#!/bin/bash
#SBATCH --job-name=Assignment02Job
#SBATCH --time=00:10:00
#SBATCH --mem=16G
#SBATCH --ntasks=10
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=5
#SBATCH --output=Assignment02Job.%j.out
#SBATCH --partition=defq

module load openmpi/4.1.5-gcc-11.20.0-ux65npg

if [ ! -f Assignment02_Output ]
then
 make
else
 if [ assignment02.c -nt Assignment02_Output ]
 then
  make
 fi
fi

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun ./Assignment02_Output 3 3

exit 0
